### ISSUE TITLE
default template suffix

### ISSUE THREAD

**Issue by minow** [zendframework/ZendDeveloperTools#94]
Using composer to install zf2 skeleton along with developer tools. After enabling it I am getting server errors, like:

```
PHP Fatal error:  Uncaught exception 'Zend\\View\\Exception\\RuntimeException' with message 'Zend\\View\\Renderer\\PhpRenderer::render: Unable to render template "zend-developer-tools/toolbar/zendframework"; resolver could not resolve to a file' in C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zendframework\\library\\Zend\\View\\Renderer\\PhpRenderer.php:499
Stack trace:
#0 C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zend-developer-tools\\src\\ZendDeveloperTools\\Listener\\ToolbarListener.php(203): Zend\\View\\Renderer\\PhpRenderer->render(Object(Zend\\View\\Model\\ViewModel))
#1 C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zend-developer-tools\\src\\ZendDeveloperTools\\Listener\\ToolbarListener.php(148): ZendDeveloperTools\\Listener\\ToolbarListener->renderEntries(Object(ZendDeveloperTools\\ProfilerEvent))
#2 C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zend-developer-tools\\src\\ZendDeveloperTools\\Listener\\ToolbarListener.php(137): ZendDeveloperTools\\Listener\\ToolbarListener->injectToolbar(Object(ZendDe in C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zendframework\\library\\Zend\\View\\Renderer\\PhpRenderer.php on line 499
```

adding 'default_template_suffix' key to module.config.php:

``` php
return array(
    'view_manager' => array(
        'default_template_suffix' => 'phtml',
        'template_path_stack' => array(
            'zenddevelopertools' => __DIR__ . '/../view',
        ),
    ),
);
```

fixes the issue.

**Comment by findli** [comment]
in my case i fix it through:
//            'zenddevelopertools' => __DIR__ . '/../view',
            'ZendDeveloperTools' => __DIR__ . '/../view',
in vendor\zendframework\zend-developer-tools\config

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas/laminas-developer-tools; a new issue has been opened at https://github.com/laminas/laminas-developer-tools/issues/23.
